blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://docs.tileserver.app
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/vinayakkulkarni/tileserver-rs/discussions
    about: Ask questions and share ideas in Discussions
